### ISSUE TITLE
sort order

### ISSUE THREAD

**Issue by punjasin** [panter/ra-data-prisma#137]
it return sort order must be object how do I fix this

query need to be

```
  "orderBy": [
    {
      "createdAt": {
        "sort": "desc"
      }
    }
  ],

```
instead of 

```
  "orderBy": [
    {
      "createdAt": "desc"
    }
  ],

```

how do I customize this :(

**Comment by macrozone** [comment]
how is the backend generated that uses that dialect?

**Comment by punjasin** [comment]
I am using prisma typegraphql generator it was working fine before since yesterday it after i add more model

**Comment by knapeto** [comment]
what version of ra-data-prisma and typegraphql are you using?

**Comment by punjasin** [comment]
it was
`"typegraphql-prisma": "^0.26.0",`"[typegraphql-prisma](https://npmjs.com/package/typegraphql-prisma)": "[^0.26.0](https://npmjs.com/package/typegraphql-prisma)",

and
on react admin i am using 
lasted one

`    queryDialect: "typegraphql",
    mutationOperationNames: {
      typegraphql: {
        [CREATE]: (resource) => `createOne${resource.name}`,
        [UPDATE]: (resource) => `updateOne${resource.name}`,
        [DELETE]: (resource) => `deleteOne${resource.name}`,
      },
    },`

**Comment by punjasin** [comment]
after i revert my yarn lock issue is resolve seem like sub version of type graphql has some breaking change broke this
i ll close the ticket
