### ISSUE TITLE
array filter does not work for n-m relations

### ISSUE THREAD

**Issue by thought2** [panter/ra-data-prisma#25]
```
const ActorFilter = (props) => (
  <Filter {...props}>
    <ReferenceArrayInput
      label="Project"
      source="projects"
      reference="Project"
      fullWidth
    >
      <AutocompleteArrayInput />
    </ReferenceArrayInput>
  </Filter>
);
```

This produces data lacking the `{some: ... }` object, leading to a request failure.

Looks like there's something wrong with the if condition in here:
https://github.com/panter/ra-data-prisma/blob/master/packages/dataprovider/src/buildWhere.ts#L143

**Comment by macrozone** [comment]
@thought2 it works for 1-n relations, maybe it does not work yet for m-n (as in your example)

If you want to do a PR, it would be nice, or i can look into it later

**Comment by macrozone** [comment]
@thought2 i fix this now.

Selecting multiple projects in your example would return Actors that (worked) on any of these Projects. So it will be an OR.
