### ISSUE TITLE
customize or extend resolvers from addCrudResolvers

### ISSUE THREAD

**Issue by bennettrogers** [panter/ra-data-prisma#26]
Is there a way to customize or extend the resolvers created by `addCrudResolvers`?

The use case I'm thinking of for this is to automatically generate slugs for e.g. a blog post model. The slug is a required string field in the schema, but if it is not provided it could be autogenerated from the post title. 

The Nexus prisma plugin provides the `resolve` arg on `t.crud` and `t.model` which allows for customizing the resolver, but addCrudResolvers just calls `t.crud` without passing any arguments.

I realize I could just skip using `addCrudResolvers` for models where I want to have this level of control, but I just wanted to see if this was a customization that had been considered.

Thank you!

**Comment by macrozone** [comment]
@bennettrogers 

maybe it would help if one could pass additional properties in `addCrudResolvers` that gets forwarded to `t.crud`? how could that look like?

maybe

```
addCrudResolvers("BlogPost", {
  customize: {
    all: orgConfig => ({
         ...orgConfig,
         resolve(...) {
            // my custom resolve
         }
     })
  }
})
```

But you actually need to modifiy the updateOne / createOne mutation.

nexus has computed inputs for that: 
https://nexusjs.org/nexus-plugins/prisma#publish-autogenerated-mutations-with-computed-input-values

so we would need


```
addCrudResolvers("BlogPost", {
  customize: {
    createOne: orgConfig => ({
         ...orgConfig,
        computedInputs: { slug: ({ args, ctx, info }) => "someslug"}
     })
  }
})
```

so customize could take the following functions:

(in case of model "BlogPost"):

`one` --> maps to t.crud.BogPost
`all` --> maps to t.crud.BogPosts // plural
`createOne` --> maps to t.crud.createOneBogPost
`updateOne` --> maps to t.crud.updateOneeBogPost
etc.

i would suggest that these functions take the original config (which is mostly empty), that makes it a bit flexibler later.



----

By the way, having computed properties would be something that would be even nicer to have in prisma. I opened up a Feature Request for that, i would be very happy if you could give it an upvote or comment: https://github.com/prisma/prisma/issues/2597

**Comment by bennettrogers** [comment]
Yes, something like this would be great in Prisma itself. I upvoted your feature request.

Your suggested approach here looks excellent to me! Nexus seems to provide a lot of functionality in the `crud` function that would be helpful to be able to access, but I really enjoy the convenience of `addCrudResolvers` so I don't have to write out every crud function for every resource myself. This looks like it would solve that issue very nicely.

One thing that I'm realizing might be a problem with this specific use case though is that since the `slug` field is marked as required in my Prisma schema, it's also getting marked as required in the generated GraphQL schema. This means that an incoming mutation request that doesn't contain a `slug` is rejected before we even get to the resolvers. I'm fairly new to GraphQL (and very new to Prisma and Nexus), so I don't understand enough about the request handling stack to know whether this is avoidable.

**Comment by macrozone** [comment]
@bennettrogers i had a similar problem once and had to work around it. 

I am not sure if [computed-inputs](https://nexusjs.org/nexus-plugins/prisma#publish-autogenerated-mutations-with-computed-input-values) do remove these props from the input type though, maybe you have to try that out

**Comment by macrozone** [comment]
@bennettrogers i added the new customize api in latest version. can you check if that works for you?

**Comment by bennettrogers** [comment]
@macrozone Yes! This works perfectly! Thank you so much!

I was just playing around with computed inputs this morning, since I hadn't come across them before your previous reply. I had just gotten them working by manually specifying my crud resolvers. And now I can use them while still maintaining the cleanliness that `addCrudResolvers` enables!

Thank you for the fast reply and feature addition. This package is making React Admin so much easier to work with.

**Comment by macrozone** [comment]
> @macrozone Yes! This works perfectly! Thank you so much!
> 
> I was just playing around with computed inputs this morning, since I hadn't come across them before your previous reply. I had just gotten them working by manually specifying my crud resolvers. And now I can use them while still maintaining the cleanliness that `addCrudResolvers` enables!
> 
> Thank you for the fast reply and feature addition. This package is making React Admin so much easier to work with.

Awesome to hear!

I did not update the readme yet, if you feel like it would be nice if you could help document it and provide your use case as an example!
