### ISSUE TITLE
Dataprovider does not support newest nexus-plugin-prisma@0.18.0

### ISSUE THREAD

**Issue by izziaraffaele** [panter/ra-data-prisma#38]
The new version of `nexus-plugin-prisma` comes with a few changes that break the dataprovider. 

Mainly I'm experiencing issues with `Int` and `Float` update input which have been changed from a simple scalar field to a custom input type but also the changes to the ordering functionalities might break the dataprovider.

**Comment by izziaraffaele** [comment]
Also the buildWhere function fails due to some changes to the naming structure of filter inputs

**Comment by macrozone** [comment]
@izziaraffaele hope to get to this soon! 

also the new case insensitive feature can be used to remove our "poor mans case insensitive search" (or make it configurable, ideally)

**Comment by izziaraffaele** [comment]
Let me know if I can help with something

**Comment by izziaraffaele** [comment]
@macrozone I published a PR which only solves bugs to make this package working with the newest nexus-plugin-prisma. Can you please have a look at it and let me know if there's something else that needs to be done?

**Comment by macrozone** [comment]
should been fixed. i open a new issue about the fulltext search
