### ISSUE TITLE
connect in update mutation

### ISSUE THREAD

**Issue by gtolarc** [panter/ra-data-prisma#46]
```javascript
<ReferenceInput label="Shop" source="shopId" reference="Shop">
    <SelectInput optionText="name" />
</ReferenceInput>
```
ReferenceInput is not automatically converted to 'connect' format. If source="shop.connect.id" is used, it works functionally, but the existing shopId is not recognized in the edit screen.

Is there a solution to this?

**Comment by gtolarc** [comment]
It seems that nexus-plugin-prisma removes relation id(in this case, shopId) from update mutation when building crud.

If this is intended, I think ReferenceInput should be automatically changed to use 'create/connect'. Or, it would be nice if there was an option to use the shopId of source for query and shop.connect.id for mutation. Like this,
```javascript
<ReferenceInput label="Shop" source="shopId" sourceOut="shop.connect.id" reference="Shop">
    <SelectInput optionText="name" />
</ReferenceInput>
```

**Comment by gtolarc** [comment]
https://github.com/marmelab/react-admin/issues/5608#issuecomment-736302293 I got this answer, can you guys fix it?

**Comment by macrozone** [comment]
@gtolarc did you try

```
<ReferenceInput label="Shop" source="shop" reference="Shop">
    <SelectInput optionText="name" />
</ReferenceInput>
```

?

**Comment by gtolarc** [comment]
yes, if source="shop" is used, it is requested as follows.
<img width="883" alt="스크린샷 2020-12-01 오후 6 28 51" src="https://user-images.githubusercontent.com/8623798/100721897-4a3d2700-3403-11eb-913a-22dc7fed49b7.png">

**Comment by gtolarc** [comment]
This is my schema.prisma
```javascript
model Shop {
  @@map(name: "shop")

  id          Int         @id @default(autoincrement())
  name        String?
  itemInfos   ItemInfo[]
}

model ItemInfo {
  @@map(name: "itemInfo")

  id          Int         @id @default(autoincrement())
  name        String?
  shopId      Int?
  shop        Shop?       @relation(fields: [shopId], references: [id])
}
```
and types
```javascript
const Shop = objectType({
  name: 'Shop',
  definition(t) {
    t.model.id();
    t.model.name();
    t.model.itemInfos();
  },
});
const ItemInfo = objectType({
  name: 'ItemInfo',
  definition(t) {
    t.model.id();
    t.model.name();
    t.model.shopId();
    t.model.shop();
  },
});
```

**Comment by gtolarc** [comment]
lib vers.
```javascript
"dependencies": {
    "@nexus/schema": "^0.19.2",
    "@prisma/client": "^2.12.1",
    "@ra-data-prisma/backend": "^4.0.0",
    "graphql": "^15.4.0",
    "nexus-plugin-prisma": "^0.25.0",
  },
  "devDependencies": {
    "@prisma/cli": "^2.12.1",
  }
```

**Comment by macrozone** [comment]
@gtolarc did you define both as Resources as described in the [readme](https://github.com/panter/ra-data-prisma/blob/master/packages/dataprovider/README.md#relations) by calling `addCrudResolvers` on both Shop and ItemInfo?

**Comment by gtolarc** [comment]
Yes, this is my related code. There seems to be a part where I made a mistake, but I don't know where it is. There seems to be no problem with the points you gave me.

```javascript
const schema = makeSchema({
  types: [
    Shop,
    addCrudResolvers('Shop'),
    ItemInfo,
    addCrudResolvers('ItemInfo'),
  ],
  plugins: [
    nexusPrisma({
      experimentalCRUD: true,
      paginationStrategy: 'prisma',
      outputs: {
        typegen: path.resolve(__dirname, 'generated/nexus-prisma.d.ts'),
      },
    }),
  ],
  outputs: {
    typegen: path.resolve(__dirname, 'generated/nexus.d.ts'),
    schema: path.resolve(__dirname, 'generated/schema.gql'),
  },
});
```

**Comment by macrozone** [comment]
@gtolarc no worries, maybe i am also wrong. I'll try to reproduce it in the project

**Comment by macrozone** [comment]
> lib vers.
> 
> ```js
> {
>   "dependencies": {
>     "@nexus/schema": "^0.19.2",
>     "@prisma/client": "^2.12.1",
>     "@ra-data-prisma/backend": "^4.0.0",
>     "graphql": "^15.4.0",
>     "nexus-plugin-prisma": "^0.25.0",
>   },
>   "devDependencies": {
>     "@prisma/cli": "^2.12.1",
>   }
> }
> ```

you do not seem to use the dataprovider, you need to use `@ra-data-prisma/dataprovider`  as well

**Comment by gtolarc** [comment]
Sorry for the confusion. The version mentioned above is what I used in the backend, and I used @ra-data-prisma/dataprovider in the front as well.

**Comment by macrozone** [comment]
@gtolarc be aware that the latest supported version of nexus-plugin-prisma is 0.18.2. support for 0.25. is planned, but i had not had the chance to do it yet

**Comment by macrozone** [comment]
@gtolarc indeed, the test ist failing with 0.25: https://github.com/panter/ra-data-prisma/pull/47

**Comment by macrozone** [comment]
@gtolarc i fixed the problem with nexus-plugin-prisma 0.25. in https://github.com/panter/ra-data-prisma/pull/47

it should be released as version 5 as its a breaking change.

**Comment by gtolarc** [comment]
Thank you! Awesome! @macrozone

**Comment by macrozone** [comment]
@gtolarc can you check if it works?

**Comment by gtolarc** [comment]
Sure, it's working properly. @macrozone
