### ISSUE TITLE
Incorrect return type on `useDataProvider`

### ISSUE THREAD

**Issue by sMteX** [panter/ra-data-prisma#95]
If I'm not mistaken, `buildDataProvider` returns the old version/interface of data provider - function `(type, resource, params) => Promise<any>` (https://github.com/panter/ra-data-prisma/blob/master/packages/dataprovider/src/buildDataProvider.ts#L36), which corresponds to React Admin's `LegacyDataProvider` (https://github.com/marmelab/react-admin/blob/master/packages/ra-core/src/types.ts#L303)

However, the return type of `useDataProvider` says `DataProvider` which has a different signature and cannot be casted (`useDataProvider() as LegacyDataProvider`). 

Workaround is something like `(useDataProvider() as unknown) as LegacyDataProvider` which isn't very nice.

**Comment by macrozone** [comment]
@sMteX you might be right, so we should probably just set its type as LegacyDataProvider
