### ISSUE TITLE
Incorrect query field with typegraphql

### ISSUE THREAD

**Issue by Alazoral** [panter/ra-data-prisma#97]
Hi there, I've been trying to get react-admin up and running with prisma and not having the greatest luck. After spending some time in dep hell trying to get nexus working, I switched to typegraphql and typegraphql-prisma. I had a lot more success with that, since react-admin starts now but it can't fetch any data, resulting in errors like these:

```json
    {
      "message": "Cannot query field \"count\" on type \"AggregateActivity\". Did you mean \"_count\"?",
      "locations": [
        {
          "line": 25,
          "column": 5
        }
      ]
    }

```

I tried changing buildGqlQuery.js:218 to `gqlTypes.field(gqlTypes.name("_count")` from `gqlTypes.field(gqlTypes.name("count")`, but that hasn't stopped it. Is there some configuration that I'm missing or something? I'm quite new to react-admin and graphql, so it definitely wouldn't shock me if I was. Thanks so much for y'all's assistance and hard work on this valuable project.

**Comment by macrozone** [comment]
>  tried changing buildGqlQuery.js:218 to gqlTypes.field(gqlTypes.name("_count") from gqlTypes.field(gqlTypes.name("count"), but that hasn't stopped it

that should work, but if you changed it directly in node_modules, you might need to restart. You can use [patch-package](https://www.npmjs.com/package/patch-package) to add the patch to your project until this is fixed

**Comment by Alazoral** [comment]
@macrozone Thanks so much, looks like that cleared up that issue.
